// Barrel: re-exports every page component. main.jsx imports pages from here.
export { ActivityPage } from './ActivityPage';
export { RealtimePage } from './RealtimePage';
export { TradesPage } from './TradesPage';
export { AdminUsers } from './AdminUsers';
export { RulesPage } from './RulesPage';
export { AdminExchanges } from './AdminExchanges';
export { AdminOpenWA } from './AdminOpenWA';
export { FundsPage } from './FundsPage';
export { BotsPage } from './BotsPage';
export { ProfilePage } from './ProfilePage';
export { MyEquityPage } from './MyEquityPage';
export { EmployeeFundPage } from './EmployeeFundPage';
export { SupportPage } from './SupportPage';
export { PricesPage } from './PricesPage';
export { StatusPage } from './StatusPage';
export { AdminReports } from './AdminReports';
export { AuditPage } from './AuditPage';
export { default as AnalysisPage } from './AnalysisPage';
export { default as PlaybookPage } from './PlaybookPage';
export { default as AnomaliesPage } from './AnomaliesPage';
export { default as CalendarPage } from './CalendarPage';
export { default as PositionPage } from './PositionPage';
export { default as GuidePage } from './GuidePage';
